default:
    autoload:
        '': %paths.base%/tests/bdd/context
    suites:
        default:
            contexts: [%paths.base%/tests/bdd/features]
    extensions:
        Laracasts\Behat:
            # env_path: .env.behat
        Behat\MinkExtension:
            default_session: laravel
            base_url: http://localhost:8888
            laravel: ~