default:
    paths:
        features: %behat.paths.base%/tests/features
        bootstrap: %behat.paths.features%/bootstrap
    extensions:
        Laracasts\Behat:
            # env_path: .env.behat
        Behat\MinkExtension:
            default_session: laravel
            base_url: http://localhost:8888
            laravel: ~